package commands

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Env handles environment variable management commands
func Env(args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("subcommand required\nUsage: lvt env <command> [args]\n\nCommands:\n  generate    Generate .env.example file")
	}

	subcommand := args[0]
	subArgs := args[1:]

	switch subcommand {
	case "generate":
		return EnvGenerate(subArgs)
	default:
		return fmt.Errorf("unknown env subcommand: %s\n\nAvailable commands:\n  generate    Generate .env.example file", subcommand)
	}
}

// EnvGenerate generates a .env.example file based on the app structure
func EnvGenerate(args []string) error {
	// Check if we're in an app directory
	if _, err := os.Stat("go.mod"); os.IsNotExist(err) {
		return fmt.Errorf("not in a LiveTemplate app directory (go.mod not found)")
	}

	// Detect features
	features := detectFeatures()

	// Generate .env content
	content := generateEnvContent(features)

	// Write to .env.example
	envFile := ".env.example"
	if err := os.WriteFile(envFile, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", envFile, err)
	}

	fmt.Printf("✅ Generated %s\n", envFile)
	fmt.Println("\nNext steps:")
	fmt.Println("1. Copy .env.example to .env:")
	fmt.Println("   cp .env.example .env")
	fmt.Println("2. Fill in your actual values in .env")
	fmt.Println("3. Never commit .env to version control")
	fmt.Println("\nTip: Add '.env' to your .gitignore if not already there")

	return nil
}

// detectFeatures analyzes the app structure to detect what features are in use
func detectFeatures() map[string]bool {
	features := map[string]bool{
		"database":  false,
		"auth":      false,
		"email":     false,
		"server":    false,
		"sessions":  false,
		"csrf":      false,
	}

	// Check for database (schema.sql or migrations)
	if _, err := os.Stat("internal/database/schema.sql"); err == nil {
		features["database"] = true
	}
	if _, err := os.Stat("internal/database/migrations"); err == nil {
		features["database"] = true
	}

	// Check for auth
	if _, err := os.Stat("internal/app/auth"); err == nil {
		features["auth"] = true
		features["sessions"] = true
		features["csrf"] = true

		// Check if email features are used
		authFiles, _ := filepath.Glob("internal/app/auth/*.go")
		for _, file := range authFiles {
			content, _ := os.ReadFile(file)
			contentStr := string(content)
			if strings.Contains(contentStr, "magic") || strings.Contains(contentStr, "confirm") || strings.Contains(contentStr, "reset") {
				features["email"] = true
				break
			}
		}
	}

	// Server is always needed
	features["server"] = true

	return features
}

// generateEnvContent generates the .env file content based on detected features
func generateEnvContent(features map[string]bool) string {
	var b strings.Builder

	b.WriteString("# LiveTemplate App Environment Variables\n")
	b.WriteString("# Generated by: lvt env generate\n")
	b.WriteString("#\n")
	b.WriteString("# Copy this file to .env and fill in your actual values:\n")
	b.WriteString("#   cp .env.example .env\n")
	b.WriteString("#\n")
	b.WriteString("# IMPORTANT: Never commit .env to version control!\n")
	b.WriteString("\n")

	// Server configuration
	if features["server"] {
		b.WriteString("# ============================================================================\n")
		b.WriteString("# Server Configuration\n")
		b.WriteString("# ============================================================================\n")
		b.WriteString("\n")
		b.WriteString("# Server port (default: 3000)\n")
		b.WriteString("PORT=3000\n")
		b.WriteString("\n")
		b.WriteString("# Server host (default: localhost, use 0.0.0.0 for all interfaces)\n")
		b.WriteString("HOST=localhost\n")
		b.WriteString("\n")
		b.WriteString("# Application environment (development, staging, production)\n")
		b.WriteString("APP_ENV=development\n")
		b.WriteString("\n")
		b.WriteString("# Application URL (used for redirects, emails, etc.)\n")
		b.WriteString("APP_URL=http://localhost:3000\n")
		b.WriteString("\n")
	}

	// Database configuration
	if features["database"] {
		b.WriteString("# ============================================================================\n")
		b.WriteString("# Database Configuration\n")
		b.WriteString("# ============================================================================\n")
		b.WriteString("\n")
		b.WriteString("# SQLite database file path (relative to app root)\n")
		b.WriteString("# For production, use an absolute path or persistent volume mount\n")
		b.WriteString("DATABASE_PATH=./dev.db\n")
		b.WriteString("\n")
		b.WriteString("# Database connection options\n")
		b.WriteString("# DB_TIMEOUT=5000\n")
		b.WriteString("# DB_MAX_OPEN_CONNS=25\n")
		b.WriteString("# DB_MAX_IDLE_CONNS=10\n")
		b.WriteString("\n")
	}

	// Auth configuration
	if features["auth"] {
		b.WriteString("# ============================================================================\n")
		b.WriteString("# Authentication Configuration\n")
		b.WriteString("# ============================================================================\n")
		b.WriteString("\n")
		b.WriteString("# Session secret key (generate with: openssl rand -hex 32)\n")
		b.WriteString("# MUST be set in production and kept secret!\n")
		b.WriteString("SESSION_SECRET=change-me-to-random-32-byte-hex\n")
		b.WriteString("\n")
		b.WriteString("# Session duration in seconds (default: 30 days)\n")
		b.WriteString("# SESSION_DURATION=2592000\n")
		b.WriteString("\n")
		if features["csrf"] {
			b.WriteString("# CSRF secret key (generate with: openssl rand -hex 32)\n")
			b.WriteString("# MUST be set in production and kept secret!\n")
			b.WriteString("CSRF_SECRET=change-me-to-random-32-byte-hex\n")
			b.WriteString("\n")
		}
	}

	// Email configuration
	if features["email"] {
		b.WriteString("# ============================================================================\n")
		b.WriteString("# Email Configuration\n")
		b.WriteString("# ============================================================================\n")
		b.WriteString("\n")
		b.WriteString("# Email provider (smtp, console, or custom)\n")
		b.WriteString("# Use 'console' for development (prints to terminal)\n")
		b.WriteString("EMAIL_PROVIDER=console\n")
		b.WriteString("\n")
		b.WriteString("# SMTP Configuration (for production)\n")
		b.WriteString("# Uncomment and configure if EMAIL_PROVIDER=smtp\n")
		b.WriteString("#\n")
		b.WriteString("# SMTP_HOST=smtp.gmail.com\n")
		b.WriteString("# SMTP_PORT=587\n")
		b.WriteString("# SMTP_USER=your-email@gmail.com\n")
		b.WriteString("# SMTP_PASS=your-app-password\n")
		b.WriteString("#\n")
		b.WriteString("# Sender email address (displayed in emails)\n")
		b.WriteString("# EMAIL_FROM=noreply@yourdomain.com\n")
		b.WriteString("# EMAIL_FROM_NAME=Your App Name\n")
		b.WriteString("\n")
		b.WriteString("# Magic link/token expiration (in minutes, default: 15)\n")
		b.WriteString("# TOKEN_EXPIRATION=15\n")
		b.WriteString("\n")
	}

	// Production-specific
	b.WriteString("# ============================================================================\n")
	b.WriteString("# Production Settings\n")
	b.WriteString("# ============================================================================\n")
	b.WriteString("\n")
	b.WriteString("# Enable production optimizations\n")
	b.WriteString("# - Template caching\n")
	b.WriteString("# - Asset minification\n")
	b.WriteString("# - Error page instead of stack traces\n")
	b.WriteString("# PRODUCTION=false\n")
	b.WriteString("\n")
	b.WriteString("# Log level (debug, info, warn, error)\n")
	b.WriteString("# LOG_LEVEL=info\n")
	b.WriteString("\n")
	b.WriteString("# Enable structured logging (JSON format)\n")
	b.WriteString("# LOG_JSON=false\n")
	b.WriteString("\n")

	// Additional services (commented out by default)
	b.WriteString("# ============================================================================\n")
	b.WriteString("# Optional: Additional Services\n")
	b.WriteString("# ============================================================================\n")
	b.WriteString("\n")
	b.WriteString("# Uncomment and configure as needed:\n")
	b.WriteString("#\n")
	b.WriteString("# Error tracking (Sentry)\n")
	b.WriteString("# SENTRY_DSN=https://...@sentry.io/...\n")
	b.WriteString("#\n")
	b.WriteString("# Analytics\n")
	b.WriteString("# ANALYTICS_ID=UA-XXXXXXXXX-X\n")
	b.WriteString("#\n")
	b.WriteString("# File storage (S3, R2, etc.)\n")
	b.WriteString("# S3_BUCKET=your-bucket-name\n")
	b.WriteString("# S3_REGION=us-east-1\n")
	b.WriteString("# S3_ACCESS_KEY_ID=...\n")
	b.WriteString("# S3_SECRET_ACCESS_KEY=...\n")
	b.WriteString("#\n")
	b.WriteString("# Redis cache\n")
	b.WriteString("# REDIS_URL=redis://localhost:6379\n")
	b.WriteString("\n")

	// Development helpers
	b.WriteString("# ============================================================================\n")
	b.WriteString("# Development Settings\n")
	b.WriteString("# ============================================================================\n")
	b.WriteString("\n")
	b.WriteString("# Enable hot reload in development\n")
	b.WriteString("# HOT_RELOAD=true\n")
	b.WriteString("\n")
	b.WriteString("# Enable debug mode (verbose logging, template debugging)\n")
	b.WriteString("# DEBUG=false\n")
	b.WriteString("\n")
	b.WriteString("# Show SQL queries in logs\n")
	b.WriteString("# SQL_DEBUG=false\n")
	b.WriteString("\n")

	// Security notes
	b.WriteString("# ============================================================================\n")
	b.WriteString("# Security Best Practices\n")
	b.WriteString("# ============================================================================\n")
	b.WriteString("#\n")
	b.WriteString("# 1. Generate strong secrets:\n")
	b.WriteString("#    openssl rand -hex 32\n")
	b.WriteString("#\n")
	b.WriteString("# 2. Never commit .env to version control:\n")
	b.WriteString("#    echo '.env' >> .gitignore\n")
	b.WriteString("#\n")
	b.WriteString("# 3. Use different secrets for each environment\n")
	b.WriteString("#\n")
	b.WriteString("# 4. Rotate secrets regularly in production\n")
	b.WriteString("#\n")
	b.WriteString("# 5. Use environment-specific .env files:\n")
	b.WriteString("#    .env.development (local dev)\n")
	b.WriteString("#    .env.staging (staging server)\n")
	b.WriteString("#    .env.production (production - managed via secrets manager)\n")
	b.WriteString("\n")

	return b.String()
}
