package unstyled

import (
	"fmt"
	"io"
	"reflect"
	"sort"
	"strings"
)

// GenerateCSS writes a scaffold CSS file with all BEM class names from the
// unstyled adapter. The output includes essential layout rules for overlay
// components and empty stubs for visual styling that users can customize.
func GenerateCSS(w io.Writer) error {
	adapter := &Adapter{}

	sections := []struct {
		name   string
		styles any
	}{
		{"Accordion", adapter.AccordionStyles()},
		{"Autocomplete", adapter.AutocompleteStyles()},
		{"Breadcrumbs", adapter.BreadcrumbsStyles()},
		{"Breadcrumb Item", adapter.BreadcrumbItemStyles()},
		{"Data Table", adapter.DatatableStyles()},
		{"Date Picker", adapter.DatepickerStyles()},
		{"Drawer", adapter.DrawerStyles()},
		{"Dropdown", adapter.DropdownStyles()},
		{"Menu", adapter.MenuStyles()},
		{"Modal", adapter.ModalStyles()},
		{"Confirm Modal", adapter.ConfirmModalStyles()},
		{"Sheet", adapter.SheetStyles()},
		{"Popover", adapter.PopoverStyles()},
		{"Progress", adapter.ProgressStyles()},
		{"Circular Progress", adapter.CircularProgressStyles()},
		{"Spinner", adapter.SpinnerStyles()},
		{"Rating", adapter.RatingStyles()},
		{"Skeleton", adapter.SkeletonStyles()},
		{"Avatar Skeleton", adapter.AvatarSkeletonStyles()},
		{"Card Skeleton", adapter.CardSkeletonStyles()},
		{"Tabs", adapter.TabsStyles()},
		{"Tags Input", adapter.TagsInputStyles()},
		{"Timeline", adapter.TimelineStyles()},
		{"Timeline Item", adapter.TimelineItemStyles()},
		{"Time Picker", adapter.TimepickerStyles()},
		{"Toast", adapter.ToastStyles()},
		{"Toggle", adapter.ToggleStyles()},
		{"Checkbox", adapter.CheckboxStyles()},
		{"Tooltip", adapter.TooltipStyles()},
	}

	fmt.Fprintln(w, "/* LiveTemplate Unstyled CSS Scaffold")
	fmt.Fprintln(w, " * Generated by: lvt styles scaffold")
	fmt.Fprintln(w, " *")
	fmt.Fprintln(w, " * This file provides BEM class stubs for all components.")
	fmt.Fprintln(w, " * Customize these rules to style your application.")
	fmt.Fprintln(w, " *")
	fmt.Fprintln(w, " * Essential layout rules (overlays, positioning) are pre-filled.")
	fmt.Fprintln(w, " * Visual rules (colors, typography, spacing) are left empty for you. */")
	fmt.Fprintln(w)

	// Utility classes
	fmt.Fprintln(w, "/* === Utilities === */")
	fmt.Fprintln(w)
	fmt.Fprintln(w, ".lvt-sr-only {")
	fmt.Fprintln(w, "  position: absolute;")
	fmt.Fprintln(w, "  width: 1px;")
	fmt.Fprintln(w, "  height: 1px;")
	fmt.Fprintln(w, "  padding: 0;")
	fmt.Fprintln(w, "  margin: -1px;")
	fmt.Fprintln(w, "  overflow: hidden;")
	fmt.Fprintln(w, "  clip: rect(0, 0, 0, 0);")
	fmt.Fprintln(w, "  white-space: nowrap;")
	fmt.Fprintln(w, "  border-width: 0;")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w)

	for _, sec := range sections {
		if err := writeSection(w, sec.name, sec.styles); err != nil {
			return err
		}
	}

	return nil
}

// essentialRules maps BEM class names to pre-filled CSS rules for layout-critical
// components (overlays, fixed positioning, etc.) that need functional CSS.
var essentialRules = map[string][]string{
	// Modal
	"lvt-modal":            {"position: fixed", "inset: 0", "z-index: 50", "overflow-y: auto"},
	"lvt-modal__overlay":   {"position: fixed", "inset: 0", "background: rgba(0,0,0,0.5)"},
	"lvt-modal__container--centered": {"display: flex", "min-height: 100%", "align-items: center", "justify-content: center", "padding: 1rem"},
	"lvt-modal__container--top":      {"display: flex", "min-height: 100%", "align-items: flex-start", "justify-content: center", "padding: 1rem", "padding-top: 4rem"},
	// Confirm Modal
	"lvt-confirm-modal":            {"position: fixed", "inset: 0", "z-index: 50", "overflow-y: auto"},
	"lvt-confirm-modal__overlay":   {"position: fixed", "inset: 0", "background: rgba(0,0,0,0.5)"},
	"lvt-confirm-modal__container": {"display: flex", "min-height: 100%", "align-items: center", "justify-content: center", "padding: 1rem"},
	// Sheet
	"lvt-sheet":          {"position: fixed", "inset: 0", "z-index: 50"},
	"lvt-sheet__overlay": {"position: fixed", "inset: 0", "background: rgba(0,0,0,0.5)"},
	"lvt-sheet__panel":   {"position: fixed"},
	// Drawer
	"lvt-drawer":          {"position: fixed", "inset: 0", "z-index: 40"},
	"lvt-drawer__overlay": {"position: fixed", "inset: 0", "background: rgba(0,0,0,0.5)"},
	"lvt-drawer__panel":   {"position: fixed"},
	// Toast
	"lvt-toast-container": {"position: fixed", "z-index: 50", "display: flex", "flex-direction: column", "gap: 0.75rem", "pointer-events: none"},
	"lvt-toast":           {"pointer-events: auto"},
}

func writeSection(w io.Writer, name string, styles any) error {
	fmt.Fprintf(w, "/* === %s === */\n\n", name)

	v := reflect.ValueOf(styles)

	// Collect all class names in order
	var classes []string
	for i := 0; i < v.NumField(); i++ {
		field := v.Field(i)
		if field.Kind() != reflect.String {
			continue
		}
		cls := field.String()
		if cls == "" {
			continue
		}
		classes = append(classes, cls)
	}

	// Deduplicate (some classes might be used for multiple fields)
	seen := make(map[string]bool)
	var unique []string
	for _, cls := range classes {
		if !seen[cls] {
			seen[cls] = true
			unique = append(unique, cls)
		}
	}

	for _, cls := range unique {
		fmt.Fprintf(w, ".%s {\n", cls)
		if rules, ok := essentialRules[cls]; ok {
			for _, rule := range rules {
				fmt.Fprintf(w, "  %s;\n", rule)
			}
		}
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w)
	}

	return nil
}

// AllClassNames returns a sorted list of all unique BEM class names
// defined by the unstyled adapter.
func AllClassNames() []string {
	adapter := &Adapter{}
	structs := []any{
		adapter.AccordionStyles(),
		adapter.AutocompleteStyles(),
		adapter.BreadcrumbsStyles(),
		adapter.BreadcrumbItemStyles(),
		adapter.DatatableStyles(),
		adapter.DatepickerStyles(),
		adapter.DrawerStyles(),
		adapter.DropdownStyles(),
		adapter.MenuStyles(),
		adapter.ModalStyles(),
		adapter.ConfirmModalStyles(),
		adapter.SheetStyles(),
		adapter.PopoverStyles(),
		adapter.ProgressStyles(),
		adapter.CircularProgressStyles(),
		adapter.SpinnerStyles(),
		adapter.RatingStyles(),
		adapter.SkeletonStyles(),
		adapter.AvatarSkeletonStyles(),
		adapter.CardSkeletonStyles(),
		adapter.TabsStyles(),
		adapter.TagsInputStyles(),
		adapter.TimelineStyles(),
		adapter.TimelineItemStyles(),
		adapter.TimepickerStyles(),
		adapter.ToastStyles(),
		adapter.ToggleStyles(),
		adapter.CheckboxStyles(),
		adapter.TooltipStyles(),
	}

	seen := make(map[string]bool)
	for _, s := range structs {
		v := reflect.ValueOf(s)
		for i := 0; i < v.NumField(); i++ {
			f := v.Field(i)
			if f.Kind() == reflect.String && f.String() != "" {
				seen[f.String()] = true
			}
		}
	}

	// Always include utility classes
	seen["lvt-sr-only"] = true

	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// ClassCount returns the total number of unique BEM class names.
func ClassCount() int {
	return len(AllClassNames())
}

// ValidateBEM checks that all class names follow the lvt-{component} BEM convention.
func ValidateBEM() []string {
	var invalid []string
	for _, name := range AllClassNames() {
		if !strings.HasPrefix(name, "lvt-") {
			invalid = append(invalid, name)
		}
	}
	return invalid
}
